version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - prod.env
    depends_on:
      - db
    command: bash -c "alembic upgrade head && python3 init_base_data.py && python3 init_test_data.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"



  db:
      image: postgres:14
      restart: on-failure
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=projects
      ports:
        - "2345:5432"
      env_file:
        - dev.env
