apiVersion: v1
kind: Service
metadata:
  name: defects-service
  labels:
    service: defects-service
spec:
  selector:
    app: defects-api
  ports:
    - name: tcp-port
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
