apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv-defects
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/data/postgres-db-pv-defects"