apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service-statistics
  labels:
    service: postgres-db-service-statistics
spec:
  selector:
    app: postgres-db-statistics
  ports:
    - name: tcp-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
