apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  labels:
    service: statistics-service
spec:
  selector:
    app: statistics-api
  ports:
    - name: tcp-port
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
